import { API_BASE_URL, apiRequest } from './apiClient';

export type PageStatus = 'Draft' | 'In Progress' | 'Completed' | 'Approved' | string;
export type TaskType = 'Background' | 'Shading' | 'Effect' | 'Screentone' | 'Clean Line' | 'Dialogue Edit';
export type TaskStatus = 'Pending' | 'In Progress' | 'Submitted' | 'Approved' | 'Revision Required' | string;

export interface Region {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface WorkspaceAssistant {
  id: string;
  name: string;
  email?: string;
  avatar?: string;
  specialties?: string[];
}

export interface WorkspaceChapter {
  id: string;
  seriesId?: string;
  number?: number;
  title: string;
}

export interface WorkspacePageItem {
  id: string;
  chapterId: string;
  pageNumber: number;
  status: PageStatus;
  imageUrl?: string;
  thumbnailUrl?: string;
  tasksCount?: number;
  completedTasksCount?: number;
  panelLayout?: number;
}

export interface WorkspaceTask {
  id: string;
  pageId: string;
  chapterId?: string;
  seriesId?: string;
  seriesTitle?: string;
  chapterTitle?: string;
  pageNumber?: number;
  title: string;
  type: TaskType;
  assistantId: string;
  assistantName?: string;
  description: string;
  deadline: string;
  price: number;
  status: TaskStatus;
  region: Region;
  submittedResult?: string;
  mangakaFeedback?: string;
  createdAt?: string;
  resourceUrls?: string[];
  assignedBy?: string;
  assignedByName?: string;
  paymentStatus?: string | null;
}

export interface WorkspacePayload {
  page: WorkspacePageItem;
  chapter?: WorkspaceChapter;
  pages: WorkspacePageItem[];
  tasks: WorkspaceTask[];
  assistants: WorkspaceAssistant[];
}

export interface CreateWorkspaceTaskInput {
  pageId: string;
  type: TaskType;
  assistantId: string;
  description: string;
  deadline: string;
  price: number;
  region: Region;
}

export interface UpdateWorkspaceTaskInput {
  title?: string;
  description?: string;
  assistantId?: string;
  deadline?: string;
  priority?: number;
  region?: Region;
}

// BE chấp nhận đúng các giá trị (phân biệt hoa thường): background, shading,
// cleanup, speech_bubble, effects, lineart, other. UI lại hiển thị nhãn riêng,
// nên cần map hai chiều để tránh lỗi 400 khi tạo task.
const TASK_TYPE_TO_API: Record<TaskType, string> = {
  'Background': 'background',
  'Shading': 'shading',
  'Effect': 'effects',
  'Screentone': 'other',
  'Clean Line': 'cleanup',
  'Dialogue Edit': 'speech_bubble',
};

const TASK_TYPE_FROM_API: Record<string, TaskType> = {
  background: 'Background',
  shading: 'Shading',
  effects: 'Effect',
  other: 'Screentone',
  cleanup: 'Clean Line',
  lineart: 'Clean Line',
  speech_bubble: 'Dialogue Edit',
};

// Nhãn tiếng Việt cho từng loại nhiệm vụ (dùng cho tiêu đề task).
const TASK_TYPE_LABEL_VI: Record<TaskType, string> = {
  'Background': 'nền',
  'Shading': 'bóng đổ',
  'Effect': 'hiệu ứng',
  'Screentone': 'screentone',
  'Clean Line': 'nét vẽ',
  'Dialogue Edit': 'thoại',
};

export function toApiTaskType(type: TaskType): string {
  return TASK_TYPE_TO_API[type] ?? 'other';
}

export function fromApiTaskType(value: string): TaskType {
  return TASK_TYPE_FROM_API[value?.toLowerCase()] ?? 'Background';
}

// Tiêu đề auto cũ (tiếng Anh) dạng "Shading: Page area" / "Effect: Page 3" → cần dịch lại.
function isAutoGeneratedTitle(title?: string | null): boolean {
  if (!title || !title.trim()) return true;
  return /:\s*Page(\s+\d+)?(\s+area)?$/i.test(title.trim());
}

/** Sinh tiêu đề task bằng tiếng Việt, vd: "Xử lý bóng đổ cho vùng trang 3". */
export function buildTaskTitleVi(type: TaskType, pageNumber?: number): string {
  const label = TASK_TYPE_LABEL_VI[type] ?? 'nội dung';
  return pageNumber
    ? `Xử lý ${label} cho vùng trang ${pageNumber}`
    : `Xử lý ${label} cho vùng đã chọn`;
}

// BE cũng kiểm tra status theo giá trị: todo, in_progress, submitted, approved, rejected.
const TASK_STATUS_TO_API: Record<string, string> = {
  'Pending': 'todo',
  'In Progress': 'in_progress',
  'Submitted': 'submitted',
  'Approved': 'approved',
  'Revision Required': 'rejected',
};

export function toApiTaskStatus(status: TaskStatus): string {
  return TASK_STATUS_TO_API[status] ?? String(status).toLowerCase();
}

type ApiEnvelope<T> = T | { data: T };

interface ApiPage {
  id: string;
  chapterId: string;
  pageNumber: number;
  imageUrl?: string | null;
  thumbnailUrl?: string | null;
  status: string;
  width?: number | null;
  height?: number | null;
}

interface ApiChapter {
  id: string;
  seriesId: string;
  chapterNumber: number;
  title?: string | null;
}

interface ApiSeries {
  id: string;
  title: string;
}

interface ApiProfile {
  id: string;
  email?: string | null;
  fullName?: string | null;
  avatarUrl?: string | null;
}

interface ApiTask {
  id: string;
  pageId: string;
  taskType: string;
  status: string;
  title?: string | null;
  description?: string | null;
  region: string;
  assignedTo?: string | null;
  assignedToName?: string | null;
  assignedBy?: string | null;
  assignedByName?: string | null;
  deadline?: string | null;
  createdAt?: string | null;
  resourceUrls?: string[] | null;
  price?: number | null;
  paymentStatus?: string | null;
}

interface ApiKanbanItem {
  id: string;
  pageId: string;
  status?: string;
}

interface ApiKanban {
  todo?: ApiKanbanItem[];
  doing?: ApiKanbanItem[];
  done?: ApiKanbanItem[];
}

function unwrap<T>(value: ApiEnvelope<T>): T {
  if (value && typeof value === 'object' && 'data' in value) {
    return (value as { data: T }).data;
  }
  return value as T;
}

function normalizeRegion(region: Region | string): Region {
  if (typeof region === 'string') {
    return JSON.parse(region) as Region;
  }
  return region;
}

function mapPageStatus(status: string): PageStatus {
  switch (status?.toLowerCase()) {
    case 'assigned':
    case 'in_progress':
      return 'In Progress';
    case 'reviewing':
      return 'Review';
    case 'completed':
    case 'approved':
      return 'Completed';
    case 'published':
      return 'Published';
    case 'draft':
    default:
      return 'Draft';
  }
}

function mapTaskStatus(status: string): TaskStatus {
  switch (status?.toLowerCase()) {
    case 'in_progress':
      return 'In Progress';
    case 'submitted':
      return 'Submitted';
    case 'approved':
      return 'Approved';
    case 'rejected':
      return 'Revision Required';
    case 'todo':
    default:
      return 'Pending';
  }
}

function mapPage(page: ApiPage): WorkspacePageItem {
  return {
    id: page.id,
    chapterId: page.chapterId,
    pageNumber: page.pageNumber,
    status: mapPageStatus(page.status),
    imageUrl: page.imageUrl ?? undefined,
    thumbnailUrl: page.thumbnailUrl ?? page.imageUrl ?? undefined,
    tasksCount: 0,
    completedTasksCount: 0,
  };
}

function mapChapter(chapter: ApiChapter): WorkspaceChapter {
  return {
    id: chapter.id,
    seriesId: chapter.seriesId,
    number: chapter.chapterNumber,
    title: chapter.title || `Chapter ${chapter.chapterNumber}`,
  };
}

function mapAssistant(profile: ApiProfile): WorkspaceAssistant {
  return {
    id: profile.id,
    name: profile.fullName || profile.email || 'Assistant',
    email: profile.email ?? undefined,
    avatar: profile.avatarUrl ?? undefined,
  };
}

function mapTask(
  task: ApiTask,
  page?: WorkspacePageItem,
  chapter?: WorkspaceChapter,
  series?: ApiSeries
): WorkspaceTask {
  const type = fromApiTaskType(task.taskType);
  return {
    id: task.id,
    pageId: task.pageId,
    chapterId: page?.chapterId ?? chapter?.id,
    seriesId: chapter?.seriesId,
    seriesTitle: series?.title,
    chapterTitle: chapter?.title,
    pageNumber: page?.pageNumber,
    title: isAutoGeneratedTitle(task.title) ? buildTaskTitleVi(type, page?.pageNumber) : task.title!,
    type,
    assistantId: task.assignedTo ?? '',
    assistantName: task.assignedToName ?? undefined,
    description: task.description ?? '',
    deadline: task.deadline?.slice(0, 10) ?? new Date().toISOString().slice(0, 10),
    price: Number(task.price) || 0,
    status: mapTaskStatus(task.status),
    region: normalizeRegion(task.region),
    createdAt: task.createdAt?.slice(0, 10),
    resourceUrls: task.resourceUrls ?? undefined,
    assignedBy: task.assignedBy ?? undefined,
    assignedByName: task.assignedByName ?? undefined,
    paymentStatus: task.paymentStatus ?? null,
  };
}

/** Upload file tham khảo cho một task (multipart). Trả về task đã cập nhật. */
export async function uploadTaskResources(taskId: string, files: File[]): Promise<WorkspaceTask> {
  const form = new FormData();
  files.forEach(file => form.append('files', file));

  const token = localStorage.getItem('inkflow_access_token');
  const response = await fetch(`${API_BASE_URL}/api/tasks/${taskId}/resources`, {
    method: 'POST',
    headers: token ? { Authorization: `Bearer ${token}` } : undefined,
    body: form,
  });

  if (!response.ok) {
    const body = await response.text();
    let message = body;
    try {
      const parsed = JSON.parse(body) as { message?: string; title?: string };
      message = parsed.message || parsed.title || body;
    } catch {
      // giữ nguyên text
    }
    throw new Error(message || `Tải file tham khảo thất bại (status ${response.status})`);
  }

  return mapTask(unwrap(await response.json()));
}

function normalizeTask(task: WorkspaceTask): WorkspaceTask {
  return {
    ...task,
    region: normalizeRegion(task.region),
    price: Number(task.price) || 0,
  };
}

export async function getWorkspace(pageId: string): Promise<WorkspacePayload> {
  const apiPage = unwrap(await apiRequest<ApiEnvelope<ApiPage>>(`/api/pages/${pageId}`));
  const page = mapPage(apiPage);
  const [apiChapter, apiPages, apiProfiles] = await Promise.all([
    apiRequest<ApiEnvelope<ApiChapter>>(`/api/chapters/${page.chapterId}`).then(unwrap),
    apiRequest<ApiEnvelope<ApiPage[]>>(`/api/chapters/${page.chapterId}/pages`).then(unwrap),
    apiRequest<ApiEnvelope<ApiProfile[]>>('/api/profiles/assistants').then(unwrap),
  ]);

  const chapter = mapChapter(apiChapter);
  const pages = apiPages.map(mapPage);
  const pageById = new Map(pages.map(item => [item.id, item]));
  const [series, kanban] = await Promise.all([
    chapter.seriesId
      ? apiRequest<ApiEnvelope<ApiSeries>>(`/api/series/${chapter.seriesId}`).then(unwrap).catch(() => undefined)
      : Promise.resolve(undefined),
    apiRequest<ApiEnvelope<ApiKanban>>(`/api/chapters/${page.chapterId}/kanban`).then(unwrap).catch(() => undefined),
  ]);

  const kanbanItems = [
    ...(kanban?.todo ?? []),
    ...(kanban?.doing ?? []),
    ...(kanban?.done ?? []),
  ];

  const apiTasks = await Promise.all(
    kanbanItems.map(item => apiRequest<ApiEnvelope<ApiTask>>(`/api/tasks/${item.id}`).then(unwrap))
  );

  const allTasks = apiTasks.map(task => mapTask(task, pageById.get(task.pageId), chapter, series));
  const tasks = allTasks.filter(task => task.pageId === pageId);
  const taskCounts = new Map<string, { total: number; completed: number }>();
  allTasks.forEach(task => {
    const count = taskCounts.get(task.pageId) ?? { total: 0, completed: 0 };
    count.total += 1;
    if (task.status === 'Approved') count.completed += 1;
    taskCounts.set(task.pageId, count);
  });

  return {
    page: pageById.get(pageId) ?? page,
    chapter,
    pages: pages.map(item => ({
      ...item,
      tasksCount: taskCounts.get(item.id)?.total ?? 0,
      completedTasksCount: taskCounts.get(item.id)?.completed ?? 0,
    })),
    tasks,
    assistants: apiProfiles.map(mapAssistant),
  };
}

export async function createWorkspaceTask(input: CreateWorkspaceTaskInput): Promise<WorkspaceTask> {
  const task = unwrap(await apiRequest<ApiEnvelope<ApiTask>>(`/api/pages/${input.pageId}/tasks`, {
    method: 'POST',
    body: JSON.stringify({
      taskType: toApiTaskType(input.type),
      assignedTo: input.assistantId || undefined,
      title: buildTaskTitleVi(input.type),
      description: input.description,
      deadline: input.deadline,
      price: input.price,
      region: JSON.stringify(input.region),
    }),
  }));

  return normalizeTask(mapTask(task));
}

export async function updateWorkspaceTask(taskId: string, input: UpdateWorkspaceTaskInput): Promise<WorkspaceTask> {
  const task = unwrap(await apiRequest<ApiEnvelope<ApiTask>>(`/api/tasks/${taskId}`, {
    method: 'PUT',
    body: JSON.stringify({
      title: input.title,
      description: input.description,
      assignedTo: input.assistantId,
      deadline: input.deadline,
      priority: input.priority,
      region: input.region ? JSON.stringify(input.region) : undefined,
    }),
  }));

  return normalizeTask(mapTask(task));
}

export async function updateWorkspaceTaskStatus(taskId: string, status: TaskStatus): Promise<WorkspaceTask> {
  const task = unwrap(await apiRequest<ApiEnvelope<ApiTask>>(`/api/tasks/${taskId}/status`, {
    method: 'PATCH',
    body: JSON.stringify({ status: toApiTaskStatus(status) }),
  }));

  return normalizeTask(mapTask(task));
}

export async function deleteWorkspaceTask(taskId: string): Promise<void> {
  await apiRequest<void>(`/api/tasks/${taskId}`, { method: 'DELETE' });
}

/** Xóa một trang manga. Chỉ mangaka tác giả hoặc admin được phép. */
export async function deleteChapterPage(pageId: string): Promise<void> {
  await apiRequest<void>(`/api/pages/${pageId}`, { method: 'DELETE' });
}

export async function getChapterPages(chapterId: string): Promise<WorkspacePageItem[]> {
  const [apiPages, kanban] = await Promise.all([
    apiRequest<ApiEnvelope<ApiPage[]>>(`/api/chapters/${chapterId}/pages`).then(unwrap),
    apiRequest<ApiEnvelope<ApiKanban>>(`/api/chapters/${chapterId}/kanban`).then(unwrap).catch(() => undefined),
  ]);

  const pages = apiPages.map(mapPage);

  // Đếm task theo từng trang từ kanban (mỗi item có pageId + status). Hoàn thành = approved.
  const items = [
    ...(kanban?.todo ?? []),
    ...(kanban?.doing ?? []),
    ...(kanban?.done ?? []),
  ];
  const counts = new Map<string, { total: number; completed: number }>();
  items.forEach(item => {
    const c = counts.get(item.pageId) ?? { total: 0, completed: 0 };
    c.total += 1;
    if (item.status?.toLowerCase() === 'approved') c.completed += 1;
    counts.set(item.pageId, c);
  });

  return pages.map(page => ({
    ...page,
    tasksCount: counts.get(page.id)?.total ?? 0,
    completedTasksCount: counts.get(page.id)?.completed ?? 0,
  }));
}

/** Tính số trang và tiến độ task thật của một chương (dùng cho danh sách chương). */
export async function getChapterTaskStats(chapterId: string): Promise<{
  pagesCount: number;
  totalTasks: number;
  progress: number;
}> {
  const pages = await getChapterPages(chapterId);
  const totalTasks = pages.reduce((sum, p) => sum + (p.tasksCount ?? 0), 0);
  const completedTasks = pages.reduce((sum, p) => sum + (p.completedTasksCount ?? 0), 0);
  const progress = totalTasks > 0
    ? Math.round((completedTasks / totalTasks) * 100)
    : 0;
  return { pagesCount: pages.length, totalTasks, progress };
}

export async function uploadChapterPage(
  chapterId: string,
  input: { file: File; pageNumber: number; width?: number; height?: number; thumbnail?: File }
): Promise<WorkspacePageItem> {
  const form = new FormData();
  form.append('file', input.file);
  form.append('pageNumber', String(input.pageNumber));
  if (input.width !== undefined) form.append('width', String(input.width));
  if (input.height !== undefined) form.append('height', String(input.height));
  if (input.thumbnail) form.append('thumbnail', input.thumbnail);

  const token = localStorage.getItem('inkflow_access_token');
  const response = await fetch(`${API_BASE_URL}/api/chapters/${chapterId}/pages`, {
    method: 'POST',
    headers: token ? { Authorization: `Bearer ${token}` } : undefined,
    body: form,
  });

  if (!response.ok) {
    const body = await response.text();
    let message = body;
    try {
      const parsed = JSON.parse(body) as { message?: string; title?: string };
      message = parsed.message || parsed.title || body;
    } catch {
      // giữ nguyên text
    }
    throw new Error(message || `Tải trang lên thất bại (status ${response.status})`);
  }

  return mapPage(unwrap(await response.json()));
}
