// <auto-generated />
using System;
using System.Collections.Generic;
using DAL.Common;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626124056_AddSeriesBoardReviewClaims")]
    partial class AddSeriesBoardReviewClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "annotation_type", new[] { "content", "dialogue", "warning", "correction", "approval" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chapter_status", new[] { "draft", "in_progress", "reviewing", "completed", "published" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "task_assigned", "submission_received", "submission_approved", "submission_rejected", "annotation_added", "deadline_warning", "ranking_warning", "board_vote" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "page_status", new[] { "draft", "assigned", "reviewing", "approved", "published" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publishing_frequency", new[] { "weekly", "monthly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "series_status", new[] { "draft", "pending_review", "approved", "publishing", "hiatus", "cancelled", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_status", new[] { "todo", "in_progress", "submitted", "approved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_type", new[] { "background", "shading", "cleanup", "speech_bubble", "effects", "lineart", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "assistant", "mangaka", "admin", "editor", "board" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vote_decision", new[] { "approve", "reject" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_data");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_data");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("activity_logs_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("DAL.Models.AiSegmentationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("InferenceTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("inference_time_ms");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("RegionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region_type");

                    b.Property<string>("SegmentationData")
                        .HasColumnType("jsonb")
                        .HasColumnName("segmentation_data");

                    b.HasKey("Id")
                        .HasName("ai_segmentation_results_pkey");

                    b.HasIndex(new[] { "SegmentationData" }, "idx_ai_segmentation_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SegmentationData" }, "idx_ai_segmentation_gin"), "gin");

                    b.HasIndex(new[] { "PageId" }, "idx_ai_segmentation_page");

                    b.ToTable("ai_segmentation_results", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AnnotationType")
                        .HasColumnType("annotation_type")
                        .HasColumnName("annotation_type");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("shape");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("annotations_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "PageId" }, "idx_annotations_page");

                    b.HasIndex(new[] { "Shape" }, "idx_annotations_shape_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Shape" }, "idx_annotations_shape_gin"), "gin");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("DAL.Models.BoardVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("BoardMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_member_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<VoteDecisionDb>("Decision")
                        .HasColumnType("vote_decision")
                        .HasColumnName("decision");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.HasKey("Id")
                        .HasName("board_votes_pkey");

                    b.HasIndex("BoardMemberId");

                    b.HasIndex(new[] { "SeriesId", "BoardMemberId" }, "board_votes_series_id_board_member_id_key")
                        .IsUnique();

                    b.ToTable("board_votes", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("ManuscriptUrl")
                        .HasColumnType("text")
                        .HasColumnName("manuscript_url");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<ChapterStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("chapter_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'draft'::chapter_status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("chapters_pkey");

                    b.HasIndex(new[] { "SeriesId", "ChapterNumber" }, "chapters_series_id_chapter_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "SeriesId" }, "idx_chapters_series");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("DAL.Models.EditorTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("unpaid")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("priority");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("region");

                    b.PrimitiveCollection<List<string>>("ResourceUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("resource_urls")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<TaskStatusDb>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("task_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'todo'::task_status");

                    b.Property<TaskTypeDb>("TaskType")
                        .HasColumnType("task_type")
                        .HasColumnName("task_type");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VnPayBankCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vnpay_bank_code");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vnpay_response_code");

                    b.Property<string>("VnPayTransactionNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vnpay_transaction_no");

                    b.Property<string>("VnPayTxnRef")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vnpay_txn_ref");

                    b.HasKey("Id")
                        .HasName("tasks_pkey");

                    b.HasIndex("AssignedBy");

                    b.HasIndex(new[] { "AssignedTo" }, "idx_tasks_assigned_to");

                    b.HasIndex(new[] { "PageId" }, "idx_tasks_page");

                    b.HasIndex(new[] { "Region" }, "idx_tasks_region_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Region" }, "idx_tasks_region_gin"), "gin");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("DAL.Models.MangakaAssistant", b =>
                {
                    b.Property<Guid>("MangakaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mangaka_id");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("MangakaId", "AssistantId")
                        .HasName("mangaka_assistants_pkey");

                    b.HasIndex(new[] { "AssistantId" }, "idx_mangaka_assistants_assistant");

                    b.ToTable("mangaka_assistants", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_notifications_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<PageStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("page_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'draft'::page_status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pages_pkey");

                    b.HasIndex(new[] { "ChapterId" }, "idx_pages_chapter");

                    b.HasIndex(new[] { "ChapterId", "PageNumber" }, "pages_chapter_id_page_number_key")
                        .IsUnique();

                    b.ToTable("pages", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<ProfileRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("profiles_pkey");

                    b.HasIndex(new[] { "Email" }, "profiles_email_key")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("DAL.Models.PublishingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<PublishingFrequency>("Frequency")
                        .HasColumnType("publishing_frequency")
                        .HasColumnName("frequency");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date")
                        .HasColumnName("publish_date");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.HasKey("Id")
                        .HasName("publishing_schedules_pkey");

                    b.HasIndex("SeriesId");

                    b.ToTable("publishing_schedules", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Ranking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<decimal?>("PopularityScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("popularity_score");

                    b.Property<int>("RankPosition")
                        .HasColumnType("integer")
                        .HasColumnName("rank_position");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<int?>("VoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vote_count");

                    b.HasKey("Id")
                        .HasName("rankings_pkey");

                    b.HasIndex(new[] { "SeriesId" }, "idx_rankings_series");

                    b.ToTable("rankings", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_id");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre");

                    b.Property<PublishingFrequency?>("PublishingFrequency")
                        .HasColumnType("publishing_frequency")
                        .HasColumnName("publishing_frequency");

                    b.Property<SeriesStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("series_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'draft'::series_status");

                    b.Property<DateTime?>("SubmittedForReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_for_review_at");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_audience");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("series_pkey");

                    b.HasIndex(new[] { "AuthorId" }, "idx_series_author");

                    b.HasIndex(new[] { "EditorId" }, "idx_series_editor");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("DAL.Models.SeriesBoardReviewClaim", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<Guid>("BoardMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_member_id");

                    b.Property<DateTime>("ClaimedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("public")
                        .HasColumnName("source");

                    b.HasKey("SeriesId", "BoardMemberId")
                        .HasName("series_board_review_claims_pkey");

                    b.HasIndex(new[] { "BoardMemberId" }, "idx_series_board_review_claims_board");

                    b.ToTable("series_board_review_claims", (string)null);
                });

            modelBuilder.Entity("DAL.Models.SeriesBoardReviewInvitation", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<Guid>("BoardMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_member_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("SeriesId", "BoardMemberId")
                        .HasName("series_board_review_invitations_pkey");

                    b.HasIndex(new[] { "BoardMemberId" }, "idx_series_board_review_invitations_board");

                    b.ToTable("series_board_review_invitations", (string)null);
                });

            modelBuilder.Entity("DAL.Models.SeriesEditorInvitation", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<Guid>("EditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("SeriesId", "EditorId")
                        .HasName("series_editor_invitations_pkey");

                    b.HasIndex(new[] { "EditorId" }, "idx_series_editor_invitations_editor");

                    b.ToTable("series_editor_invitations", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AssistantId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<TaskStatusDb>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("task_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'submitted'::task_status");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<int?>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("submissions_pkey");

                    b.HasIndex("AssistantId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "TaskId" }, "idx_submissions_task");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ActivityLog", b =>
                {
                    b.HasOne("DAL.Models.Profile", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("activity_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.AiSegmentationResult", b =>
                {
                    b.HasOne("DAL.Models.Page", "Page")
                        .WithMany("AiSegmentationResults")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("ai_segmentation_results_page_id_fkey");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DAL.Models.Annotation", b =>
                {
                    b.HasOne("DAL.Models.Profile", "CreatedByNavigation")
                        .WithMany("Annotations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("annotations_created_by_fkey");

                    b.HasOne("DAL.Models.Page", "Page")
                        .WithMany("Annotations")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("annotations_page_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DAL.Models.BoardVote", b =>
                {
                    b.HasOne("DAL.Models.Profile", "BoardMember")
                        .WithMany("BoardVotes")
                        .HasForeignKey("BoardMemberId")
                        .HasConstraintName("board_votes_board_member_id_fkey");

                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany("BoardVotes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("board_votes_series_id_fkey");

                    b.Navigation("BoardMember");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.Chapter", b =>
                {
                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chapters_series_id_fkey");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.EditorTask", b =>
                {
                    b.HasOne("DAL.Models.Profile", "AssignedByNavigation")
                        .WithMany("TaskAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("tasks_assigned_by_fkey");

                    b.HasOne("DAL.Models.Profile", "AssignedToNavigation")
                        .WithMany("TaskAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("tasks_assigned_to_fkey");

                    b.HasOne("DAL.Models.Page", "Page")
                        .WithMany("Tasks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tasks_page_id_fkey");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DAL.Models.MangakaAssistant", b =>
                {
                    b.HasOne("DAL.Models.Profile", "Assistant")
                        .WithMany("AssistantMangakas")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mangaka_assistants_assistant_id_fkey");

                    b.HasOne("DAL.Models.Profile", "Mangaka")
                        .WithMany("MangakaAssistants")
                        .HasForeignKey("MangakaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mangaka_assistants_mangaka_id_fkey");

                    b.Navigation("Assistant");

                    b.Navigation("Mangaka");
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.HasOne("DAL.Models.Profile", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Page", b =>
                {
                    b.HasOne("DAL.Models.Chapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pages_chapter_id_fkey");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("DAL.Models.PublishingSchedule", b =>
                {
                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany("PublishingSchedules")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("publishing_schedules_series_id_fkey");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.Ranking", b =>
                {
                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany("Rankings")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rankings_series_id_fkey");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.Series", b =>
                {
                    b.HasOne("DAL.Models.Profile", "Author")
                        .WithMany("SeriesAuthors")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("series_author_id_fkey");

                    b.HasOne("DAL.Models.Profile", "Editor")
                        .WithMany("SeriesEditors")
                        .HasForeignKey("EditorId")
                        .HasConstraintName("series_editor_id_fkey");

                    b.Navigation("Author");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("DAL.Models.SeriesBoardReviewClaim", b =>
                {
                    b.HasOne("DAL.Models.Profile", "BoardMember")
                        .WithMany()
                        .HasForeignKey("BoardMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("series_board_review_claims_board_member_id_fkey");

                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("series_board_review_claims_series_id_fkey");

                    b.Navigation("BoardMember");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.SeriesBoardReviewInvitation", b =>
                {
                    b.HasOne("DAL.Models.Profile", "BoardMember")
                        .WithMany()
                        .HasForeignKey("BoardMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("series_board_review_invitations_board_member_id_fkey");

                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("series_board_review_invitations_series_id_fkey");

                    b.Navigation("BoardMember");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.SeriesEditorInvitation", b =>
                {
                    b.HasOne("DAL.Models.Profile", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("series_editor_invitations_editor_id_fkey");

                    b.HasOne("DAL.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("series_editor_invitations_series_id_fkey");

                    b.Navigation("Editor");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DAL.Models.Submission", b =>
                {
                    b.HasOne("DAL.Models.Profile", "Assistant")
                        .WithMany("SubmissionAssistants")
                        .HasForeignKey("AssistantId")
                        .HasConstraintName("submissions_assistant_id_fkey");

                    b.HasOne("DAL.Models.Profile", "ReviewedByNavigation")
                        .WithMany("SubmissionReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("submissions_reviewed_by_fkey");

                    b.HasOne("DAL.Models.EditorTask", "Task")
                        .WithMany("Submissions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("submissions_task_id_fkey");

                    b.Navigation("Assistant");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DAL.Models.Chapter", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DAL.Models.EditorTask", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DAL.Models.Page", b =>
                {
                    b.Navigation("AiSegmentationResults");

                    b.Navigation("Annotations");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DAL.Models.Profile", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Annotations");

                    b.Navigation("AssistantMangakas");

                    b.Navigation("BoardVotes");

                    b.Navigation("MangakaAssistants");

                    b.Navigation("Notifications");

                    b.Navigation("SeriesAuthors");

                    b.Navigation("SeriesEditors");

                    b.Navigation("SubmissionAssistants");

                    b.Navigation("SubmissionReviewedByNavigations");

                    b.Navigation("TaskAssignedByNavigations");

                    b.Navigation("TaskAssignedToNavigations");
                });

            modelBuilder.Entity("DAL.Models.Series", b =>
                {
                    b.Navigation("BoardVotes");

                    b.Navigation("Chapters");

                    b.Navigation("PublishingSchedules");

                    b.Navigation("Rankings");
                });
#pragma warning restore 612, 618
        }
    }
}
